name: Feature Request
description: Suggest a new feature for our robot code
title: "[FEATURE] 🚀 "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request

  - type: textarea
    id: feature_description
    attributes:
      label: Describe your suggested feature
      description: Please provide a detailed description of the feature you’re suggesting, including its functionality and any specific use cases.
      placeholder: Describe the feature in detail

  - type: textarea
    id: improvement_description
    attributes:
      label: How can this improve our overall design or robot performance?
      description: Explain how the suggested feature will enhance the design of our system or improve the robot's performance.
      placeholder: Describe the potential improvement

  - type: textarea
    id: related_problem
    attributes:
      label: Is your feature request related to a current robot problem?
      description: If applicable, describe the problem you are trying to solve with this feature request.
      placeholder: Describe the problem this feature addresses

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: If you have any additional information, sketches, or references that can help in understanding your request.
      placeholder: Add any extra information here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the boxes below to ensure you've included all necessary information.
      options:
        - label: I have described the feature and its use cases.
        - label: I have outlined how it will improve design or performance.
        - label: I have explained the problem this feature aims to solve.
